"""add folders

Revision ID: b3beac450923
Revises: bc32f13b31e3
Create Date: 2025-05-06 18:39:50.021795

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from file_storage.main.config import DB_SCHEMA  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "b3beac450923"
down_revision: Union[str, None] = "bc32f13b31e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "folders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("TIMEZONE('Europe/Moscow', now())"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("TIMEZONE('Europe/Moscow', now())"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_folders")),
        schema="files_schema",
    )
    op.create_index(
        "idx_folders_id_hash", "folders", ["id"], unique=False, schema="files_schema", postgresql_using="hash"
    )
    op.create_index(op.f("ix_files_schema_folders_name"), "folders", ["name"], unique=True, schema="files_schema")
    op.create_foreign_key(
        op.f("fk_files_folder_name_folders"),
        "files",
        "folders",
        ["folder_name"],
        ["name"],
        source_schema="files_schema",
        referent_schema="files_schema",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_files_folder_name_folders"), "files", schema="files_schema", type_="foreignkey")
    op.drop_index(op.f("ix_files_schema_folders_name"), table_name="folders", schema="files_schema")
    op.drop_index("idx_folders_id_hash", table_name="folders", schema="files_schema", postgresql_using="hash")
    op.drop_table("folders", schema="files_schema")
    # ### end Alembic commands ###
