"""init

Revision ID: bc32f13b31e3
Revises:
Create Date: 2025-05-03 01:32:05.093811

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

from file_storage.main.config import DB_SCHEMA  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "bc32f13b31e3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS files_schema")

    # Create table
    op.create_table(
        'files',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, index=True, unique=True),
        sa.Column('name', sa.Text(), index=True, nullable=False),
        sa.Column('file_name', sa.Text(), nullable=False),
        sa.Column('folder_name', sa.Text(), sa.ForeignKey('folders.name', ondelete='SET NULL'), nullable=True),
        sa.Column('size', sa.Integer(), nullable=False),
        sa.Column('path', sa.Text(), nullable=False, unique=True),
        sa.Index('idx_files_id_hash', 'id', postgresql_using='hash'),
        sa.UniqueConstraint('name', 'folder_name', name='uq_files_name_folder'),
        schema='files_schema'
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files', schema='files_schema')
    op.execute("DROP SCHEMA IF EXISTS files_schema CASCADE")
    # ### end Alembic commands ###
