"""folder_name_unique

Revision ID: 4b6641fe6104
Revises: 876071a3c1ed
Create Date: 2025-05-11 23:34:19.596002

"""

from typing import Sequence, Union

from alembic import op

from file_storage.main.config import DB_SCHEMA  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "4b6641fe6104"
down_revision: Union[str, None] = "876071a3c1ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_files_name_folder", "files", ["name", "folder_name"], schema="files_schema")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_files_name_folder", "files", schema="files_schema", type_="unique")
    # ### end Alembic commands ###
