"""init

Revision ID: bc32f13b31e3
Revises:
Create Date: 2025-05-03 01:32:05.093811

"""

from typing import Sequence, Union

from alembic import op

from file_storage.main.config import DB_SCHEMA  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "bc32f13b31e3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA files_schema")
    op.drop_index("idx_reports_id_hash", table_name="files", schema="files_schema", postgresql_using="hash")
    op.create_index("idx_files_id_hash", "files", ["id"], unique=False, schema="files_schema", postgresql_using="hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_files_id_hash", table_name="files", schema="files_schema", postgresql_using="hash")
    op.create_index(
        "idx_reports_id_hash", "files", ["id"], unique=False, schema="files_schema", postgresql_using="hash"
    )
    # ### end Alembic commands ###
