"""add folders description

Revision ID: 199c22bc09c3
Revises: b3beac450923
Create Date: 2025-05-06 22:57:50.180163

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from file_storage.main.config import DB_SCHEMA  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "199c22bc09c3"
down_revision: Union[str, None] = "b3beac450923"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("folders", sa.Column("description", sa.String(), nullable=False), schema="files_schema")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("folders", "description", schema="files_schema")
    # ### end Alembic commands ###
