"""add name and unique path

Revision ID: 876071a3c1ed
Revises: 199c22bc09c3
Create Date: 2025-05-09 15:53:58.175279

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from file_storage.main.config import DB_SCHEMA  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "876071a3c1ed"
down_revision: Union[str, None] = "199c22bc09c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("file_name", sa.String(), nullable=False), schema="files_schema")
    op.create_index(op.f("ix_files_schema_files_id"), "files", ["id"], unique=False, schema="files_schema")
    op.create_unique_constraint(op.f("uq_files_path"), "files", ["path"], schema="files_schema")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_files_path"), "files", schema="files_schema", type_="unique")
    op.drop_index(op.f("ix_files_schema_files_id"), table_name="files", schema="files_schema")
    op.drop_column("files", "file_name", schema="files_schema")
    # ### end Alembic commands ###
