"""add name and unique path

Revision ID: 876071a3c1ed
Revises: 199c22bc09c3
Create Date: 2025-05-09 15:53:58.175279

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from file_storage.main.config import DB_SCHEMA  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "876071a3c1ed"
down_revision: Union[str, None] = "199c22bc09c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
